name: CI

on:
 push:
  branches: [ dev ]


jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: RÃ©cuperation du code
      uses: actions/checkout@v2

    - name: Node.js installation
      uses: actions/setup-node@v3

    - name: Installation de npm
      uses: npm install

    - name: Lancement de tests npm
      uses: npm test


